name: rest_api_client
description: Tools to create REST-resource clients
version: 0.0.1
homepage: https://github.com/alexd1971/rest_api_client
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  data_model:
    git:
      url: https://github.com/alexd1971/data_model.git
      ref: master
  http: ^0.12.0
  
dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  